from __future__ import annotations

import json
from dataclasses import asdict
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from pydantic import BaseModel

from postsynth.config import GenerationConfig, OpenRouterConfig
from postsynth.schemas import DatasetKind


def write_jsonl(path: Path, rows: list[BaseModel]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as file:
        for row in rows:
            file.write(json.dumps(row.model_dump(), ensure_ascii=False) + "\n")


def dataset_card_path(path: Path) -> Path:
    if path.suffix:
        return path.with_suffix(".dataset.md")
    return path.with_name(path.name + ".dataset.md")


def write_dataset_card(
    path: Path,
    *,
    kind: DatasetKind,
    rows_written: int,
    source_mode: str,
    provider_config: OpenRouterConfig,
    generation_config: GenerationConfig,
    validation_stats: dict[str, Any],
    batch_diagnostics: list[dict[str, Any]] | None = None,
) -> None:
    card_path = dataset_card_path(path)
    card_path.parent.mkdir(parents=True, exist_ok=True)
    provider = _redact_provider_config(provider_config)
    generation = asdict(generation_config)
    generated_at = datetime.now(timezone.utc).isoformat()
    content = f"""# Synthetic {kind.upper()} Dataset

Generated by `postsynth`.

## Summary

- Dataset type: `{kind}`
- TRL format: conversational JSONL
- Rows written: {rows_written}
- Source mode: `{source_mode}`
- Generated at: `{generated_at}`

## Provider

```json
{json.dumps(provider, indent=2, sort_keys=True)}
```

## Generation

```json
{json.dumps(generation, indent=2, sort_keys=True)}
```

## Validation

```json
{json.dumps(validation_stats, indent=2, sort_keys=True)}
```

## Batches

```json
{json.dumps(batch_diagnostics or [], indent=2, sort_keys=True)}
```
"""
    card_path.write_text(content, encoding="utf-8")


def _redact_provider_config(config: OpenRouterConfig) -> dict[str, Any]:
    data = asdict(config)
    data["api_key"] = "<redacted>" if config.api_key else None
    return data
